/**
 * The tampered-ledger corpus oracle.
 *
 * A corpus of tampered fixtures is only worth anything if it goes RED when the
 * verifier stops catching something. That requires three properties, and this
 * file exists to enforce all three:
 *
 *   1. EXACT expectations. Every vector declares its complete finding multiset.
 *      `some(f => f.check === x)` would stay green while the verifier grew a
 *      spurious second finding or downgraded a severity, so it is never used.
 *   2. MINIMALITY. Each tampered ledger must differ from the shared clean
 *      baseline in exactly the paths its manifest entry declares. That is what
 *      makes the baseline a genuine near-neighbour control for every vector:
 *      the fixture and its control share one topology and differ by one fact,
 *      so a passing vector proves the verifier recognised the violated
 *      invariant rather than merely recognising a fixture's shape.
 *   3. CLOSED-WORLD COVERAGE. Every check the verifier can emit is named by
 *      some vector, and the check inventory is re-derived from source rather
 *      than trusted, so adding a check without a fixture fails here.
 *
 * The corpus is regenerated by `scripts/generate-corpus.ts` followed by
 * `scripts/generate-discussion-corpus.mjs` — two steps, both required. See
 * `test/fixtures/corpus/README.md` for the sequence and
 * `test/corpus-generator-guard.test.ts` for what happens when only step 1 runs.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { verifyMeshData } from "../src/verify.js";
import { loadDataFromFile } from "../src/core.js";
import {
  WORK_RECEIPT_FIXTURES,
  fixtureCheckIds,
  runFixture,
} from "./work-receipt-fixtures.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const CORPUS = join(__dirname, "fixtures", "corpus");
const SRC = join(ROOT, "src");

type Finding = { severity: string; check: string; subject: string };
type Op = { op: "set" | "delete" | "push"; path: string; value?: unknown };
type Vector = {
  id: string;
  primary: string;
  classification: "caught" | "anomaly" | "undetectable";
  lie: string;
  ops: Op[];
  expected_ok: boolean;
  expected_findings: Finding[];
};

const manifest: { now: number; baseline: string; vectors: Vector[] } = JSON.parse(
  readFileSync(join(CORPUS, "manifest.json"), "utf-8")
);

/** Pinned. A corpus whose expectations depend on Date.now() is a time bomb. */
const NOW = manifest.now;

/**
 * Loads a corpus fixture through the REAL loader, but fails loudly when the file
 * is absent. `loadDataFromFile` deliberately returns an empty ledger for a
 * missing path (correct for a fresh install, where there is nothing to read),
 * and that is exactly how a fixture reference can rot unnoticed: the file is
 * deleted or never committed, the loader hands back an empty ledger, and the
 * test keeps passing against nothing.
 */
function loadCorpusFixture(name: string) {
  const file = join(CORPUS, `${name}.json`);
  assert.ok(existsSync(file), `corpus fixture ${name}.json is missing — a corpus that loads nothing proves nothing`);
  return loadDataFromFile(file);
}

function normalize(findings: readonly { severity: string; check: string; subject: string }[]): Finding[] {
  return findings
    .map((f) => ({ severity: f.severity, check: f.check, subject: f.subject }))
    .sort((a, b) => `${a.check}${a.subject}`.localeCompare(`${b.check}${b.subject}`));
}

function applyOps(data: any, ops: Op[]): void {
  for (const { op, path, value } of ops) {
    const parts = path.split("|");
    const last = parts.pop() as string;
    let node = data;
    for (const p of parts) node = node[p];
    if (op === "set") node[last] = value;
    else if (op === "delete") delete node[last];
    else if (op === "push") node[last].push(value);
  }
}

// --------------------------------------------------------------------------
// The baseline is the control every vector is measured against.
// --------------------------------------------------------------------------

test("corpus baseline is a clean ledger: zero findings, ok", () => {
  const report = verifyMeshData(loadCorpusFixture("baseline") as any, NOW);
  assert.deepEqual(normalize(report.findings), [], "the shared control must be clean or every vector's delta is unattributable");
  assert.equal(report.ok, true);
});

test("the corpus is non-empty and every vector has a distinct id", () => {
  assert.ok(manifest.vectors.length >= 40, `expected a substantive corpus, got ${manifest.vectors.length}`);
  const ids = manifest.vectors.map((v) => v.id);
  assert.equal(new Set(ids).size, ids.length, "duplicate vector ids");
});

// --------------------------------------------------------------------------
// Per-vector: exact findings, and provable minimality against the baseline.
// --------------------------------------------------------------------------

for (const v of manifest.vectors) {
  test(`[${v.classification}] ${v.id} — ${v.lie}`, () => {
    const data = loadCorpusFixture(v.id);
    const report = verifyMeshData(data as any, NOW);

    // (1) EXACT multiset — not `some()`, not a length check.
    assert.deepEqual(
      normalize(report.findings),
      v.expected_findings,
      `${v.id}: findings drifted from the manifest`
    );
    assert.equal(report.ok, v.expected_ok, `${v.id}: ok flag drifted`);

    // (2) The authored classification invariant. expected_findings is a
    //     regression tripwire captured from the verifier; THIS is the claim a
    //     human made about what the vector means, and it is what must hold.
    if (v.classification === "caught") {
      assert.equal(report.ok, false, `${v.id}: a caught vector must fail the ledger`);
      assert.ok(
        report.findings.some((f) => f.check === v.primary && f.severity === "error"),
        `${v.id}: must raise ERROR ${v.primary} — an overclaim that only warns is not caught`
      );
    } else if (v.classification === "anomaly") {
      assert.ok(
        report.findings.some((f) => f.check === v.primary && f.severity === "warning"),
        `${v.id}: must raise WARNING ${v.primary}`
      );
    } else {
      // The honest boundary, made executable. If this ever goes red because the
      // verifier LEARNED to catch the vector, that is good news — reclassify it
      // deliberately rather than deleting the assertion.
      assert.deepEqual(
        normalize(report.findings),
        [],
        `${v.id}: documented as undetectable by the unsigned local core, but the verifier produced findings — reclassify it as caught`
      );
      assert.equal(report.ok, true);
    }

    // (3) MINIMALITY: the fixture is exactly baseline + the declared ops.
    const rebuilt = JSON.parse(readFileSync(join(CORPUS, "baseline.json"), "utf-8"));
    applyOps(rebuilt, v.ops);
    const onDisk = JSON.parse(readFileSync(join(CORPUS, `${v.id}.json`), "utf-8"));
    assert.deepEqual(
      onDisk,
      rebuilt,
      `${v.id}: fixture is not baseline + its declared ops — an undeclared edit means the vector no longer isolates one fact`
    );
  });
}

// --------------------------------------------------------------------------
// Guarding the guard. Three of this repo's completeness guards have silently
// under-covered; an oracle that cannot fail is the same failure again.
// --------------------------------------------------------------------------

/**
 * Runs the exact comparison a per-vector test performs. The meta-test below
 * feeds it deliberately wrong expectations and requires it to throw — so what is
 * exercised is the oracle's real assertion path, not a fact about `deepEqual`.
 *
 * The load-bearing evidence for "this corpus goes red when detection regresses"
 * is not this test: it is that disabling `receipt.non_recipient_ack` in
 * `src/verify.ts` fails that vector, and deleting the check together with its id
 * additionally fails both inventory guards below. This test pins the narrower
 * property that the comparison itself tolerates no drift.
 */
function oracleCompare(actual: Finding[], expected: Finding[]): void {
  assert.deepEqual(actual, expected);
}

test("the oracle's own comparison rejects every class of drifted expectation", () => {
  let exercised = 0;
  for (const v of manifest.vectors) {
    const actual = normalize(verifyMeshData(loadCorpusFixture(v.id) as any, NOW).findings);

    // Sanity: the truth must pass, or the mutations below prove nothing.
    oracleCompare(actual, v.expected_findings);

    // Drift A — a finding goes missing (a check stopped firing).
    if (actual.length > 0) {
      assert.throws(
        () => oracleCompare(actual, actual.slice(1)),
        `${v.id}: the oracle tolerated a MISSING finding`
      );
      exercised++;
    }

    // Drift B — a spurious finding appears. Must be rejected for EVERY vector,
    // including the undetectable ones; that is what pins their emptiness and is
    // precisely what a `some(...)` style assertion would sleep through.
    assert.throws(
      () => oracleCompare(actual, [...actual, { severity: "error", check: "receipt.orphan_message", subject: "planted" }]),
      `${v.id}: the oracle tolerated an EXTRA finding`
    );

    // Drift C — severity downgraded. An error quietly becoming a warning turns a
    // caught overclaim into a passing ledger, so this must never be tolerated.
    if (actual.length > 0) {
      assert.throws(
        () => oracleCompare(actual, actual.map((f, i) =>
          i === 0 ? { ...f, severity: f.severity === "error" ? "warning" : "error" } : f
        )),
        `${v.id}: the oracle tolerated a SEVERITY FLIP`
      );
    }
  }
  assert.ok(exercised >= 36, `expected the drift checks to exercise the findings-bearing vectors, got ${exercised}`);
});

test("minimality checking actually catches an undeclared edit", () => {
  // Prove property (3) above is not vacuous: plant an edit the ops do not
  // declare and confirm the comparison rejects it.
  const v = manifest.vectors.find((x) => x.classification === "caught")!;
  const rebuilt = JSON.parse(readFileSync(join(CORPUS, "baseline.json"), "utf-8"));
  applyOps(rebuilt, v.ops);
  const smuggled = JSON.parse(JSON.stringify(rebuilt));
  smuggled.agents.a1.role = "SmuggledRole";
  assert.notDeepEqual(smuggled, rebuilt, "the minimality comparison must reject an undeclared edit");
});

// --------------------------------------------------------------------------
// Closed-world coverage. The inventory is re-derived from source, because a
// hand-maintained list of checks is exactly the thing that goes stale.
// --------------------------------------------------------------------------

/**
 * Extracts every check id the verifier can emit. Deliberately multiline-aware:
 * a line-oriented scan of this file silently misses `error(\n  "check.id",` and
 * reported 26 checks when there are 38. The self-test below pins that.
 */
function scanEmittedChecks(source: string): Set<string> {
  const out = new Set<string>();
  const re = /\b(?:error|warning)\(\s*"([a-z][a-z_]*\.[a-z_]+)"/gs;
  for (const m of source.matchAll(re)) out.add(m[1]);
  return out;
}

/**
 * Enumerates the `discussion.<code>` checks that verify.ts emits through the
 * dynamic `error(\`discussion.${finding.code}\`)` / `warning(...)` template
 * pass-through. The scanner's literal-quote regex cannot see these, so this
 * helper reads DISCUSSION_ERROR_CODES from verify.ts (same module, same
 * source) and adds them to the universe — exactly mirroring what the runtime
 * verifier can produce.
 */
function scanEmittedDiscussionChecks(): Set<string> {
  const out = new Set<string>();
  const verifySource = readFileSync(join(SRC, "verify.ts"), "utf-8");
  const codeRe = /DISCUSSION_ERROR_CODES[^;]*\[([^\]]+)\]/s;
  const codeBlock = verifySource.match(codeRe);
  if (!codeBlock) return out;
  for (const m of codeBlock[1].matchAll(/"([a-z_]+)"/g)) out.add(`discussion.${m[1]}`);
  return out;
}

test("the check scanner sees multi-line emit calls (self-test of the guard)", () => {
  const sameLine = `error("alpha.one", key, "d");`;
  const multiLine = `error(\n        "beta.two",\n        key,\n        "d"\n      );`;
  const found = scanEmittedChecks(`${sameLine}\n${multiLine}`);
  assert.ok(found.has("alpha.one"), "scanner missed a same-line emit");
  assert.ok(
    found.has("beta.two"),
    "scanner missed a MULTI-LINE emit — this is the exact blindness that undercounted the inventory as 26"
  );
});

test("every check the verifier emits is named by a corpus vector or a work-receipt fixture", () => {
  const emitted = scanEmittedChecks(readFileSync(join(SRC, "verify.ts"), "utf-8"));
  // The discussion.* family is emitted dynamically from the discussion module's
  // own codes and carries its own tamper corpus (tampered-discussion-*.json).
  // The work_receipt.* family is emitted by verify.ts but reads from the
  // SQLite work_receipts collection (not MeshData), so it cannot live in the
  // MeshData corpus manifest. It is covered by an EXECUTABLE fixture table
  // (test/work-receipt-fixtures.ts) that plants a real SQLite row for each
  // check, runs verifyLedgerFile, and asserts the named check fires. The
  // fixture table is the coverage contract — a comment saying the right word
  // cannot satisfy it, because each fixture is exercised at gate time.
  const meshDataCovered = new Set(
    manifest.vectors.map((v) => v.primary).filter(Boolean),
  );
  const sqliteCovered = fixtureCheckIds();
  const covered = new Set([...meshDataCovered, ...sqliteCovered]);

  // Subtract discussion.* — the dynamic pass-through is enumerated by the
  // helper below — and assert every remaining emitted check is covered.
  const dynamic = scanEmittedDiscussionChecks();
  const requiredUniverse = new Set<string>();
  for (const c of emitted) requiredUniverse.add(c);
  for (const c of dynamic) requiredUniverse.add(c);

  const uncovered = [...requiredUniverse]
    .filter((c) => !c.startsWith("discussion."))
    .filter((c) => !covered.has(c));
  assert.deepEqual(
    uncovered,
    [],
    `these checks can fire but no corpus vector pins them: ${uncovered.join(", ")}`,
  );
  assert.ok(
    requiredUniverse.size >= 38,
    `inventory shrank to ${requiredUniverse.size} — did a check get deleted?`,
  );
});

/**
 * The work_receipt.* fixtures must match the emitted work_receipt.* checks
 * exactly. A new check added to verify.ts without a fixture entry trips the
 * gate; a fixture entry whose check the verifier no longer emits also trips
 * it. Comments cannot satisfy this — the table is read at gate time and
 * cross-checked against the source-derived emitted set.
 */
test("work_receipt fixture table matches the verifier's emitted inventory exactly", () => {
  const emittedWr = [...scanEmittedChecks(readFileSync(join(SRC, "verify.ts"), "utf-8"))]
    .filter((c) => c.startsWith("work_receipt."))
    .sort();
  const fixtures = [...fixtureCheckIds()].sort();
  assert.deepEqual(
    fixtures,
    emittedWr,
    `fixture table drifts from emitted work_receipt.* checks: fixture=${fixtures.join(",")} emitted=${emittedWr.join(",")}`,
  );
});

/**
 * Each fixture must actually fire its named check at error severity against
 * a fresh SQLite ledger. This is the executable counterpart to the inventory
 * test above: an entry can match by name only if its plant function
 * demonstrably produces the finding it claims to pin.
 */
for (const fixture of WORK_RECEIPT_FIXTURES) {
  test(`work_receipt fixture fires: ${fixture.check} — ${fixture.description}`, () => {
    const errors = runFixture(fixture);
    const fired = errors.find((f) => f.check === fixture.check);
    assert.ok(fired, `${fixture.check}: fixture did not raise its named check; produced ${errors.map((e) => e.check).join(",")}`);
    assert.equal(fired.severity, "error");
  });
}

test("every corpus vector targets a check the verifier can still emit", () => {
  const verifySource = readFileSync(join(SRC, "verify.ts"), "utf-8");
  const emitted = scanEmittedChecks(verifySource);
  for (const c of scanEmittedDiscussionChecks()) emitted.add(c);
  // The fixture table cross-checks work_receipt.* keys above; here we treat
  // the whole vector primary set uniformly. If a future change ever adds a
  // work_receipt.* primary to the MeshData manifest (rather than relying on
  // the SQLite fixture table), the universal stale check below will refuse
  // to silently keep it — and if a check id was retired from verify.ts, the
  // stale-vector gate fires for it too.
  const stale = [...new Set(manifest.vectors.map((v) => v.primary).filter(Boolean))]
    .filter((c) => !emitted.has(c));
  assert.deepEqual(stale, [], `corpus targets checks that no longer exist: ${stale.join(", ")}`);
  // Sanity: every fixture key is emitted. A fixture for a check verify.ts
  // no longer emits is itself a stale coverage claim.
  for (const c of fixtureCheckIds()) {
    assert.ok(
      emitted.has(c),
      `work_receipt fixture table pins a check the verifier no longer emits: ${c}`,
    );
  }
});

test("coverage is reported in separate buckets, never as one blended total", () => {
  const caught = manifest.vectors.filter((v) => v.classification === "caught");
  const anomaly = manifest.vectors.filter((v) => v.classification === "anomaly");
  const undetectable = manifest.vectors.filter((v) => v.classification === "undetectable");

  // Undetectable vectors must never be counted as coverage of a check: they
  // exist to document what the free core CANNOT see. Blending them into a
  // "34/34 covered" figure would turn the corpus into marketing.
  for (const v of undetectable) {
    assert.equal(v.primary, "", `${v.id}: an undetectable vector must not claim a covered check`);
    assert.deepEqual(v.expected_findings, [], `${v.id}: an undetectable vector must expect zero findings`);
  }
  assert.ok(caught.length >= 26, `caught bucket thinned to ${caught.length}`);
  assert.ok(anomaly.length >= 10, `anomaly bucket thinned to ${anomaly.length}`);
  assert.ok(undetectable.length >= 9, `undetectable bucket thinned to ${undetectable.length}`);
});

test("published README corpus and check counts match generated and source truth", () => {
  const rootReadme = readFileSync(join(ROOT, "README.md"), "utf-8");
  const corpusReadme = readFileSync(join(CORPUS, "README.md"), "utf-8");
  const counts = {
    caught: manifest.vectors.filter((v) => v.classification === "caught").length,
    anomaly: manifest.vectors.filter((v) => v.classification === "anomaly").length,
    undetectable: manifest.vectors.filter((v) => v.classification === "undetectable").length,
  };
  // The corpus README names every emitted check the verifier can raise,
  // across BOTH paths: MeshData corpus vectors AND the SQLite-backed
  // work_receipt.* fixture table. discussion.* is excluded — the README
  // documents it separately, and the corpus's claim is about the in-memory
  // path plus the work-receipt gate, not the dynamic pass-through.
  // The emitted set from scanEmittedChecks already includes work_receipt.*
  // (they are written by error("...") calls in verify.ts), so the total here
  // is the non-discussion emitted count WITHOUT an extra fixture addition.
  const emitted = scanEmittedChecks(readFileSync(join(SRC, "verify.ts"), "utf-8"));
  const coreChecks = [...emitted].filter((check) => !check.startsWith("discussion.")).length;

  assert.match(rootReadme, new RegExp(`corpus of ${manifest.vectors.length} deliberately`));
  for (const [classification, count] of Object.entries(counts)) {
    const row = `| \`${classification}\` | ${count} |`;
    assert.ok(rootReadme.includes(row), `root README count drifted: expected ${row}`);
    assert.ok(corpusReadme.includes(row), `corpus README count drifted: expected ${row}`);
  }
  assert.ok(
    corpusReadme.includes(`name **all ${coreChecks}** checks`),
    `corpus README emitted-check count drifted: expected ${coreChecks}`,
  );
});

test("every caught vector is an overclaim and every anomaly vector is not", () => {
  for (const v of manifest.vectors) {
    if (v.classification === "caught") {
      assert.equal(v.expected_ok, false, `${v.id}: caught implies ok:false`);
      assert.ok(
        v.expected_findings.some((f) => f.severity === "error"),
        `${v.id}: caught implies at least one error`
      );
    }
    if (v.classification === "anomaly") {
      assert.ok(
        v.expected_findings.some((f) => f.check === v.primary && f.severity === "warning"),
        `${v.id}: anomaly implies its primary check warns`
      );
    }
  }
});
