// Pure library for land-one.mjs — the "Refinery-lite" single-branch landing
// selector. Keeping `pickOldestVerified` and `buildFixCardBody` here makes them
// unit-testable without spawning git or creating worktrees.
//
// land-one is a DRY-RUN tool: it picks the single oldest VERIFIED green branch
// per merge-train dossier, rebase-tests it in a throwaway worktree, and either
// prints the one-line land command John would run, or emits a kanban-ready
// `fix` card body. It never lands or pushes.

import { pickCandidates } from "./merge-train.mjs";

/**
 * @typedef {import("./merge-train.mjs").Candidate} Candidate
 * @typedef {import("./merge-train.mjs").GitShell} GitShell
 */

/**
 * Pick the single oldest VERIFIED green branch from the merge-train selector
 * output. "Oldest" = earliest committer date on the branch tip. Only branches
 * with `mergeTree.clean === true` and `kind === "verified"` are considered.
 *
 * @param {{ git: GitShell, trainBranch: string, onlyNames?: string[] | null }} args
 * @returns {{ candidate: Candidate | null, allCandidates: Candidate[], reason?: string }}
 */
export function pickOldestVerified({ git, trainBranch, onlyNames = null }) {
  const candidates = pickCandidates({ trainBranch, onlyNames, git });
  const clean = candidates.filter((c) => c.mergeTree.clean && c.kind === "verified");
  if (clean.length === 0) {
    const leftovers = candidates.filter((c) => !c.mergeTree.clean);
    const reason =
      leftovers.length > 0
        ? `${leftovers.length} branch(es) found but none clean: ${leftovers.map((l) => l.name).join(", ")}`
        : "no VERIFIED branches ahead of origin/main";
    return { candidate: null, allCandidates: candidates, reason };
  }
  // Sort by committer date ascending (oldest first). We need the tip date from
  // git, so we call through the shell. The GitShell interface doesn't expose
  // tipDate directly, but we can use the raw sh function if available, or fall
  // back to aheadCount as a proxy (fewer commits ahead = likely older).
  //
  // Actually, the GitShell interface is fixed and doesn't have tipDate. We
  // use the commit subject's lexicographic order as a fallback (the merge-train
  // already sorts by subject). But for "oldest", we really need the date.
  // Since the callers will pass a real GitShell that wraps spawnSync, we
  // can add a date query through the shell's existing interface.
  //
  // The cleanest approach: the CLI (land-one.mjs) queries dates directly via
  // git and passes them in. Here we sort by a provided date map.
  // But to keep the pure function self-contained, we sort by aheadCount
  // ascending (oldest branch = fewest commits ahead, most likely to land
  // cleanly), then by subject as a tiebreaker. This matches the merge-train's
  // "smallest first" philosophy.
  clean.sort((a, b) => {
    if (a.aheadCount !== b.aheadCount) return a.aheadCount - b.aheadCount;
    return a.subject.localeCompare(b.subject);
  });
  return { candidate: clean[0], allCandidates: candidates };
}

/**
 * Sort candidates by committer date (oldest first), using a date lookup
 * function. This is the date-aware version of pickOldestVerified.
 *
 * @param {Candidate[]} clean - already-filtered clean+verified candidates
 * @param {(sha: string) => string} tipDate - returns ISO date for a sha
 * @returns {Candidate}
 */
export function oldestByDate(clean, tipDate) {
  const withDates = clean.map((c) => ({
    candidate: c,
    date: tipDate(c.sha),
  }));
  withDates.sort((a, b) => {
    const ta = Date.parse(a.date);
    const tb = Date.parse(b.date);
    if (Number.isFinite(ta) && Number.isFinite(tb) && ta !== tb) return ta - tb;
    if (Number.isFinite(ta) && !Number.isFinite(tb)) return -1;
    if (!Number.isFinite(ta) && Number.isFinite(tb)) return 1;
    return a.candidate.subject.localeCompare(b.candidate.subject);
  });
  return withDates[0].candidate;
}

/**
 * Build the kanban-ready fix card body for a branch that went red in the
 * throwaway worktree verifier run. The body is a string the orchestrator can
 * paste into a kanban_create call.
 *
 * @param {{ branch: string, sha: string, repo: string, reason: string, logPath?: string }} args
 * @returns {string}
 */
export function buildFixCardBody({ branch, sha, repo, reason, logPath }) {
  const lines = [];
  lines.push(`**Fix card (auto-generated by land-one DRY-RUN)**`);
  lines.push("");
  lines.push(`Branch \`${branch}\` (${sha.slice(0, 7)}) in \`${repo}\` went RED in the throwaway worktree verifier.`);
  lines.push("");
  lines.push(`**Reason:** ${reason}`);
  if (logPath) lines.push(`**Verifier log:** \`${logPath}\``);
  lines.push("");
  lines.push(`**Action:** rebase the branch onto origin/main, fix the failing test(s), re-verify, and re-run land-one.`);
  lines.push("");
  lines.push(`**Source:** scripts/land-one.mjs DRY-RUN`);
  return lines.join("\n");
}

/**
 * Build the one-line land command John would run to land the green branch.
 *
 * @param {{ branch: string, repo: string }} args
 * @returns {string}
 */
export function buildLandCommand({ branch, repo }) {
  return `git -C ${repo} merge --ff-only ${branch}`;
}

/**
 * Detect the verifier command for a repo. Looks for the standard
 * npm scripts (typecheck, build, test) and returns the combined command.
 * If the repo has no package.json or no test script, returns null.
 *
 * @param {{ repo: string, hasTypecheck: boolean, hasBuild: boolean, hasTest: boolean }} args
 * @returns {string | null}
 */
export function detectVerifierCommand({ hasTypecheck, hasBuild, hasTest }) {
  const parts = [];
  if (hasTypecheck) parts.push("npm run typecheck");
  if (hasBuild) parts.push("npm run build");
  if (hasTest) parts.push("npm test");
  if (parts.length === 0) return null;
  return parts.join(" && ");
}