import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { BarrierError, canonicalJson, evaluateBytes } from "./evaluator.mjs";
const here = dirname(fileURLToPath(import.meta.url)), corpusPath = join(here, "corpus/v0.1/cases.json");
const sha = (v) => createHash("sha256").update(v).digest("hex");
function resultFor(c) { const bytes = c.raw_base64 ? Buffer.from(c.raw_base64, "base64") : Buffer.from(JSON.stringify(c.input), "utf8"); try { const output = evaluateBytes(bytes); if (c.expected_error) throw new Error(`expected ${c.expected_error}`); if (canonicalJson(output) !== canonicalJson(c.expected)) throw new Error("frozen expectation mismatch"); return { id: c.id, output }; } catch (e) { if (!(e instanceof BarrierError)) throw e; if (e.code !== c.expected_error) throw new Error(`${c.id}: expected ${c.expected_error}, got ${e.code}`); return { error: e.code, id: c.id }; } }
function runCorpus() { const raw = readFileSync(corpusPath); const corpus = JSON.parse(raw); const results = corpus.cases.map(resultFor); return { corpus_sha256: sha(raw), mandatory: corpus.cases.filter(c => c.mandatory).length, passed: results.length, profile: corpus.profile, results, total: results.length }; }
function selfTest() { const nested = (n) => `${"[".repeat(n)}0${"]".repeat(n)}`; const sized = (n) => Buffer.from(`{"a":"${"x".repeat(n - 8)}"}`); const profile = "meshfleet.a2a.dependency-join-barrier.v0.1"; const controls = [
  { raw_base64: "/w==", expected_error: "INVALID_UTF8" }, { raw_base64: Buffer.from([0xef, 0xbb, 0xbf, 0x7b, 0x7d]).toString("base64"), expected_error: "MALFORMED_JSON" }, { raw_base64: Buffer.from('{"a":').toString("base64"), expected_error: "MALFORMED_JSON" }, { raw_base64: Buffer.from('{"a":1,"a":2}').toString("base64"), expected_error: "DUPLICATE_MEMBER" },
  { raw_base64: Buffer.from('{"a":1.5}').toString("base64"), expected_error: "NON_CANONICAL_INTEGER" }, { raw_base64: Buffer.from('{"a":-0}').toString("base64"), expected_error: "NON_CANONICAL_INTEGER" }, { raw_base64: Buffer.from('{"a":9007199254740992}').toString("base64"), expected_error: "UNSAFE_INTEGER" }, { raw_base64: Buffer.from('{"a":"\\ud83d\\ude00"}').toString("base64"), expected_error: "MISSING_FIELD" }, { raw_base64: Buffer.from('{"a":"\\ud800"}').toString("base64"), expected_error: "INVALID_UNICODE" },
  { raw_base64: Buffer.from(nested(64)).toString("base64"), expected_error: "INVALID_FIELD" }, { raw_base64: Buffer.from(nested(65)).toString("base64"), expected_error: "DEPTH_LIMIT" }, { raw_base64: sized(131072).toString("base64"), expected_error: "MISSING_FIELD" }, { raw_base64: sized(131073).toString("base64"), expected_error: "SIZE_LIMIT" },
  { input: { profile, members: ["a", "a"], child_states: [], mode: "not-a-mode", extra: true }, expected_error: "UNKNOWN_FIELD" }, { input: { profile, members: ["a"], child_states: [], mode: "not-a-mode" }, expected_error: "MISSING_MEMBER" }
]; for (const c of controls) resultFor({ ...c, id: "self" }); return { controls: controls.length, profile, self_test: "passed" }; }
function receipt(bytes) { try { return { output: evaluateBytes(bytes) }; } catch (e) { if (e instanceof BarrierError) return { error: e.code }; throw e; } }
if (process.argv.includes("--stdin")) { const bytes = readFileSync(0); if (process.argv.includes("--receipt")) process.stdout.write(canonicalJson(receipt(bytes))); else { const value = receipt(bytes); if (value.error) { process.stderr.write(`${value.error}\n`); process.exitCode = 2; } else process.stdout.write(canonicalJson(value.output)); } }
else process.stdout.write(`${canonicalJson(process.argv.includes("--self-test") ? selfTest() : runCorpus())}\n`);
